version: '3.7'
services:
  my_bot:
    image: message_to_xamzaaff:latest
    env_file:
      - ./.env
    restart: on_failure
    ports:
      - "6379:6379"
  bot:
    build: .
    command: sh -c "make migrate && python -m bot"
    env_file:
      - ./.env
    restart: always